### PR TITLE
Send Content-Type only if there is data, relative post location

### PR DESCRIPTION
**Pull request by bancek**
Sorry for two fixes in single pull request.

`PUT` and `DELETE` methods should only send `Content-type` header if there request has data.

If `Location` header is not full URL (doesn't start with http/s) it can be passed as `id` parameter and `url_join` function will join `Location` with `base_path`.

### CODE REVIEW

**Comment by atlithorn** [comment]
Can we not get this merged?
Is slumber no longer active?

**Comment by samgiles** [comment]
@alithorn still "active", maintenance mostly - I'll get this merged when I get a moment.

**Comment by atlithorn** [comment]
@samgiles I apologize if I sound(ed) presumptuous. Starting a large project and I seriously appreciate the abstraction you are providing but I'm shit scared of having to support a branch of my own if it takes 3 years to get a good change merged...

**Comment by samgiles** [comment]
The content-type issue is now in master, tracking the location stuff in https://github.com/samgiles/slumber/issues/138, will need to check test coverage.

**Pull request closed without merging**
