### PR TITLE
Allow subclassing Resource

### PR DESCRIPTION
**Pull request by koterpillar**

### CODE REVIEW

**Comment by davidfischer-ch** [comment]
I implemented an alternative and more generic version of this idea in 48a494b7ea6954f0df1a4a08c2b074d3190a125a

**Comment by koterpillar** [comment]
@davidfischer-ch would you like to pull in the test?

**Comment by davidfischer-ch** [comment]
Yes!

**Comment by samgiles** [comment]
Merged in the test and davidfischer-ch's change.  Thanks!

**Pull request closed without merging**
